/**
 * API Forge — code generation + live runtime factories.
 *
 * generateBotScript / generateMiniAI emit deployable handler source
 * (route-handler style, following the serverless-template function
 * layout and cloudnative-template validation-error phrasing).
 *
 * createBotHandler / createMiniAIHandler return LIVE handlers that run
 * in-app immediately — the generated entity API works the moment the
 * Forge produces it, no deploy step required.
 */

import { ApiOperation, EntityDescriptor, ForgeHandler, GeneratedApi } from './types';

/* ------------------------------------------------------------------ */
/* Validation (cloudnative-template error phrasing)                    */
/* ------------------------------------------------------------------ */

export function validatePayload(
  entity: EntityDescriptor,
  payload: Record<string, unknown>,
  partial = false,
): string[] {
  const errors: string[] = [];
  for (const field of entity.fields) {
    const value = payload[field.name];
    if (value === undefined || value === null) {
      if (field.required && !partial && field.semantic !== 'id' && field.semantic !== 'date') {
        errors.push(`${field.name} is required`);
      }
      continue;
    }
    const t = typeof value;
    if (field.semantic === 'number' && t !== 'number') {
      errors.push(`${field.name} must be of type number`);
    } else if (field.semantic === 'boolean' && t !== 'boolean') {
      errors.push(`${field.name} must be of type boolean`);
    } else if (
      ['text', 'freetext', 'email', 'id', 'ref', 'enum'].includes(field.semantic) &&
      t !== 'string'
    ) {
      errors.push(`${field.name} must be of type string`);
    }
    if (field.semantic === 'email' && t === 'string' && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(value as string)) {
      errors.push(`${field.name} must be a valid email`);
    }
  }
  return errors;
}

/* ------------------------------------------------------------------ */
/* Bot script                                                          */
/* ------------------------------------------------------------------ */

export function generateBotScript(entity: EntityDescriptor, ops: ApiOperation[]): GeneratedApi {
  const E = entity.name;
  const code = `// ${E} API — bot script generated by API Forge
// Deterministic CRUD. Validation follows cloudnative-template conventions.
import { createBotHandler } from '@/lib/apiForge/generator';
import { ${E}Entity } from './entities';

export const ${E}Api = createBotHandler(${E}Entity);

// Route table (mount in any Express/Fastify/edge router):
${ops
  .map((op) => {
    switch (op) {
      case 'list':   return `// GET    /${E}s          -> ${E}Api.invoke('list')`;
      case 'get':    return `// GET    /${E}s/:id      -> ${E}Api.invoke('get', { id })`;
      case 'create': return `// POST   /${E}s          -> ${E}Api.invoke('create', body)`;
      case 'update': return `// PATCH  /${E}s/:id      -> ${E}Api.invoke('update', { id, ...body })`;
      case 'delete': return `// DELETE /${E}s/:id      -> ${E}Api.invoke('delete', { id })`;
      case 'query':  return `// POST   /${E}s/query    -> ${E}Api.invoke('query', { where })`;
    }
  })
  .join('\n')}
`;
  return {
    entity: E,
    verdict: 'bot-script',
    operations: ops,
    code,
    generatedAt: new Date().toISOString(),
  };
}

export function createBotHandler(entity: EntityDescriptor): ForgeHandler {
  const rows = new Map<string, Record<string, unknown>>();
  let seq = 0;

  return {
    entity: entity.name,
    verdict: 'bot-script',
    async invoke(op, payload = {}) {
      switch (op) {
        case 'list':
          return [...rows.values()];
        case 'get': {
          const row = rows.get(String(payload.id));
          if (!row) throw new Error(`${entity.name} not found`);
          return row;
        }
        case 'create': {
          const errors = validatePayload(entity, payload);
          if (errors.length) throw new Error(errors.join('; '));
          const id = payload.id != null ? String(payload.id) : `${entity.name}-${++seq}`;
          const row = { ...payload, id, createdAt: new Date().toISOString() };
          rows.set(id, row);
          return row;
        }
        case 'update': {
          const id = String(payload.id);
          const existing = rows.get(id);
          if (!existing) throw new Error(`${entity.name} not found`);
          const errors = validatePayload(entity, payload, true);
          if (errors.length) throw new Error(errors.join('; '));
          const row = { ...existing, ...payload, id, updatedAt: new Date().toISOString() };
          rows.set(id, row);
          return row;
        }
        case 'delete': {
          const id = String(payload.id);
          if (!rows.delete(id)) throw new Error(`${entity.name} not found`);
          return { deleted: id };
        }
        case 'query': {
          const where = (payload.where ?? {}) as Record<string, unknown>;
          return [...rows.values()].filter((row) =>
            Object.entries(where).every(([k, v]) => row[k] === v),
          );
        }
        default:
          throw new Error(`unsupported operation: ${op}`);
      }
    },
  };
}

/* ------------------------------------------------------------------ */
/* Mini AI                                                             */
/* ------------------------------------------------------------------ */

/** Signature of the chat function the mini AI routes through (freeAIChat). */
export type ChatFn = (
  messages: { role: 'system' | 'user' | 'assistant'; content: string }[],
  options?: { model?: string; provider?: string },
) => Promise<{ content: string }>;

export function buildMiniAIContract(entity: EntityDescriptor): string {
  const fieldLines = entity.fields
    .map((f) => `- ${f.name}: ${f.type}${f.required ? '' : ' (optional)'} [${f.semantic}]`)
    .join('\n');
  return `You are the ${entity.name} API — a mini AI generated by API Forge.
You manage ${entity.name} records with this schema:
${fieldLines}

Rules:
- Respond ONLY with a JSON object: {"ok": true, "result": ...} or {"ok": false, "error": "..."}.
- Validate every input against the schema before acting.
- For "query" operations, interpret natural-language filters against the record set you are given.
- Never invent fields that are not in the schema.`;
}

export function generateMiniAI(entity: EntityDescriptor, ops: ApiOperation[]): GeneratedApi {
  const E = entity.name;
  const code = `// ${E} API — mini AI generated by API Forge
// LLM-backed adapter through the Free AI router (Groq → OpenRouter → Ollama).
import { createMiniAIHandler, buildMiniAIContract } from '@/lib/apiForge/generator';
import { freeAIChat } from '@/lib/freeAI/client';
import { ${E}Entity } from './entities';

export const ${E}Api = createMiniAIHandler(${E}Entity, (messages, options) =>
  freeAIChat(messages, options),
);

// System contract shipped to the model on every call:
/*
${buildMiniAIContract(entity)}
*/
// Operations: ${ops.join(', ')}
`;
  return {
    entity: E,
    verdict: 'mini-ai',
    operations: ops,
    code,
    generatedAt: new Date().toISOString(),
  };
}

export function createMiniAIHandler(entity: EntityDescriptor, chat: ChatFn): ForgeHandler {
  // The mini AI keeps the same deterministic store underneath — the LLM
  // interprets intent (especially query), the store stays authoritative.
  const bot = createBotHandler(entity);
  const contract = buildMiniAIContract(entity);

  return {
    entity: entity.name,
    verdict: 'mini-ai',
    async invoke(op, payload = {}) {
      if (op !== 'query') return bot.invoke(op, payload);

      const rows = (await bot.invoke('list')) as unknown[];
      const question = String(payload.q ?? payload.where ?? '');
      const reply = await chat([
        { role: 'system', content: contract },
        {
          role: 'user',
          content: `Operation: query\nFilter: ${question}\nRecords: ${JSON.stringify(rows)}`,
        },
      ]);
      try {
        const parsed = JSON.parse(reply.content);
        if (parsed.ok === false) throw new Error(parsed.error);
        return parsed.result ?? parsed;
      } catch {
        // Model returned non-JSON — fall back to the deterministic path.
        return bot.invoke('query', typeof payload.where === 'object' ? payload : {});
      }
    },
  };
}
